from datetime import datetime

class FinalReportGenerator:
    """
    Menggabungkan seluruh hasil diagnostic menjadi
    laporan markdown siap kirim ke klien.
    """

    def __init__(
        self,
        dataset_name: str,
        summary: dict,
        scores: dict,
        risk: dict,
        business_impact: dict,
        recommendations: dict
    ):
        self.dataset_name = dataset_name
        self.summary = summary
        self.scores = scores
        self.risk = risk
        self.business_impact = business_impact
        self.recommendations = recommendations

    def generate_markdown(self) -> str:
        date_str = datetime.now().strftime("%Y-%m-%d")

        md = f"""# Raw Data Diagnostic Report

**Dataset**: {self.dataset_name}  
**Tanggal Analisis**: {date_str}

---

## 1. Ringkasan Kondisi Data
{self.summary.get("overview", "Ringkasan tidak tersedia")}

---

## 2. Skor Kualitas Data
- **Skor Total Dataset**: {self.scores.get("dataset_score", "N/A")} / 100

### Skor per Kolom
"""
        for col, score in self.scores.get("column_scores", {}).items():
            md += f"- {col}: {score}/100\n"

        md += f"""
---

## 3. Tingkat Risiko Data
**Kategori Risiko**: {self.risk.get("risk_level", "UNKNOWN")}

---

## 4. Dampak Bisnis Potensial
"""
        for impact in self.business_impact.get("business_impacts", []):
            md += f"- {impact}\n"

        md += """
---

## 5. Rekomendasi Langkah Lanjutan
"""
        for rec in self.recommendations.get("recommendations", []):
            md += f"- {rec}\n"

        md += """
---

## Catatan Penting
Laporan ini bersifat **diagnostik**.
Tidak ada perubahan atau pembersihan data
yang dilakukan pada tahap ini.

Keputusan penggunaan data sepenuhnya berada
di tangan pemilik data.

---

*Report generated by Raw Data Diagnostic Engine*
"""
        return md
